### ISSUE TITLE
App crashes on Mac

### ISSUE THREAD

**Issue by arendjr** [Couch-Chilis/sudoku-pi#12]
One of my colleagues reported the app crashes immediately when he tried to use it on his Mac. Need to investigate.

**Comment by mockersf** [comment]
I can reproduce, but the only logs I found are:
```
default	19:36:23.891693+0200	kernel	Sudoku Pi[14499] Corpse failure, too many 6
default	19:36:23.891700+0200	kernel	Process[14499] crashed: Sudoku Pi. Too many corpses being created.
```

**Comment by arendjr** [comment]
Current TestFlight build no longer crashes on Mac (@flenter). Seems the issue was in `winit`, creating a PR for them now.
