### ISSUE TITLE
app stops sound from background app when starting

### ISSUE THREAD

**Issue by mockersf** [Couch-Chilis/sudoku-pi#13]
when starting the app while sound is played from another (music, podcast, ...), sound from the other app is stopped

**Comment by arendjr** [comment]
Can confirm. That's quite annoying, especially since the app doesn't need sound :sweat_smile:

**Comment by ciyuxu** [comment]
Ah, today one of my friend also request that if youtube can be played in the background while playing this app. Glad someone already mentioned this.

**Comment by mockersf** [comment]
an easy fix if you don't intend to have sound should be to build Bevy without any audio feature

**Comment by arendjr** [comment]
I can confirm the latest build we have in TestFlight lets the Music app continue playing in the background. If everything else seems fine, we’ll push to the App Store this week.

**Comment by arendjr** [comment]
It’s live in the App Store now!
